export const ADD_CART_ITEMS = 'ADD_CART_ITEMS'

export const REMOVE_CART_ITEMS = 'REMOVE_CART_ITEMS'

export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS'

export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'

export const CLEAR_CART='CLEAR_CART'