export const CREATE_ORDER_REQUEST='CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS='CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE='CREATE_ORDER_FAILURE'

export const CLEAR_ORDER_SUCCESS='CLEAR_ORDER_SUCCESS'

export const GET_ORDER_REQUEST='GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS='GET_ORDER_SUCCESS'
export const GET_ORDER_FAILURE='GET_ORDER_FAILURE'

export const LIST_MY_ORDERS_REQUEST='LIST_MY_ORDERS_REQUEST'
export const LIST_MY_ORDERS_SUCCESS='LIST_MY_ORDERS_SUCCESS'
export const LIST_MY_ORDERS_FAILURE='LIST_MY_ORDERS_FAILURE'
export const LIST_MY_ORDERS_RESET='LIST_MY_ORDERS_RESET'

export const PAY_ORDER_REQUEST='PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS='PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAILURE='PAY_ORDER_FAILURE'
export const PAY_ORDER_RESET='PAY_ORDER_RESET'

export const GET_ALL_ORDERS_REQUEST='GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS='GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAILURE='GET_ALL_ORDERS_FAILURE'

export const DELIEVER_ORDER_REQUEST='DELIEVER_ORDER_REQUEST'
export const DELIEVER_ORDER_SUCCESS='DELIEVER_ORDER_SUCCESS'
export const DELIEVER_ORDER_FAILURE='DELIEVER_ORDER_FAILURE'
export const DELIEVER_ORDER_RESET='DELIEVER_ORDER_RESET'