export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE='USER_LOGIN_FAILURE'

export const USER_LOGOUT='USER_LOGOUT'

export const USER_REGIISTER_REQUEST='USER_REGIISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE='USER_REGISTER_FAILURE'

export const USER_PROFILE_REQUEST='USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS='USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAILURE='USER_PROFILE_FAILURE'
export const USER_PROFILE_RESET='USER_PROFILE_RESET'

export const USER_UPDATE_PROFILE_REQUEST='USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS='USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAILURE='USER_UPDATE_PROFILE_FAILURE'
export const USER_UPDATE_PROFILE_RESET='USER_UPDATE_PROFILE_RESET'

export const GET_ALL_USERS_REQUEST='GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS='GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAILURE='GET_ALL_USERS_FAILURE'
export const GET_ALL_USERS_RESET='GET_ALL_USERS_RESET'

export const DELETE_USER_REQUEST='DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE='DELETE_USER_FAILURE'

export const ADMIN_GET_USER_REQUEST='ADMIN_GET_USER_REQUEST'
export const ADMIN_GET_USER_SUCCESS='ADMIN_GET_USER_SUCCESS'
export const ADMIN_GET_USER_FAILURE='ADMIN_GET_USER_FAILURE'

export const ADMIN_UPDATE_USER_REQUEST='ADMIN_UPDATE_USER_REQUEST'
export const ADMIN_UPDATE_USER_SUCCESS='ADMIN_UPDATE_USER_SUCCESS'
export const ADMIN_UPDATE_USER_FAILURE='ADMIN_UPDATE_USER_FAILURE'
export const ADMIN_UPDATE_USER_RESET='ADMIN_UPDATE_USER_RESET'